### ISSUE TITLE
Github action not returning results Output for Terraform

### ISSUE THREAD

**Issue by chokhareganesh** [bridgecrewio/checkov-action#104]
while referring output from Github action, Its returning empty result output 
[https://github.com/bridgecrewio/checkov-action/blob/7659cc40e76ef92e33d630efbca5011e9afcb4e6/action.yml#L100-L102](https://github.com/bridgecrewio/checkov-action/blob/7659cc40e76ef92e33d630efbca5011e9afcb4e6/action.yml#L100-L102)

and I'm using below step to get result 
```
    steps:
    - id: checkout
      uses: actions/checkout@v3

    - name: Run Checkov action
      id: checkov
      continue-on-error: true
      uses: bridgecrewio/checkov-action@master
      with:
        directory: master/
        framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}

    - name: Print Result
      run: |
        echo "printing result"
        echo ${{ steps.checkov.outputs.results }}
```
