### ISSUE TITLE
Is it possible to optionally skip pulling docker image?

### ISSUE THREAD

**Issue by audunsolemdal** [bridgecrewio/checkov-action#110]
Currently I have a terraform reuseable workflow for my github organization. By default we run checkov on pull_request, as long as the optional input variable "skipCheckov" is not set to something else

```yaml
      - name: Run Checkov action
        if: ${{ github.event_name == 'pull_request' && inputs.skipCheckov == 'false' }}
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1810.0
        with:
          file: plan.json
          quiet: false # optional: display only failed checks
          soft_fail: true # run soft-fail to avoid stopping any workflows during implementation
          framework: terraform_plan
          download_external_modules: false
          container_user: 1000
```

The skip logic works fine, but this step runs regardless

![image](https://user-images.githubusercontent.com/21334768/200589631-ec73c32e-dddf-47ab-9555-cb60ce435750.png)

We have some runners without access to docker and/or network access, causing the job to fail.
It also unnecessarily slows down the workflows when running other triggers of the tf-plan (e.g. workflow_dispatch)

My question is - is there any way or workaround to skip pulling the docker image if: ${{ something something }}?
