### ISSUE TITLE
github runner permission issue

### ISSUE THREAD

**Issue by jnahelou** [bridgecrewio/checkov-action#122]
#117 and #121 introduced a permission issue when github runner does not run with root permissions.
Files created by action are owned by root, not by the runner user.

Steps to reproduce:
1. Create a dummy terraform file to validate
2. Add the following sample
3. Run on a github runner that runs as non-root user
```
name: checkov
on:
  workflow_dispatch:

#env:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          soft_fail: true
          output_format: github_failed_only
          download_external_modules: false
          container_user: 1
      - run: ls -all
```

Once the folder is created as root, github is unable to remove the working dir.

My workaround:
- Disable output folder (behavior prior changes) user `output_file_path: ""`

I tried using `container_user` but the option seems to be ignored.
