### ISSUE TITLE
Adding Checkov in Github Actions

### ISSUE THREAD

**Issue by rusherr02** [bridgecrewio/checkov-action#142]
**Describe the issue**
I have added below code in **_checkov.yaml*_* which is in a private branch and I pushed that code.
Now I need to integrate checkov github action with my terraform, what I need to do next?

```
---
name: Checkov
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: templates
          framework: terraform

```
![Screenshot 2023-07-11 at 11 18 30 AM](https://github.com/bridgecrewio/checkov/assets/46245426/9edd4e67-29f4-47f1-a642-19de6a5f39aa)

help me integrate checkov in github actions.
thanks!
