### ISSUE TITLE
Feature Request: Support --external-checks-XXX 

### ISSUE THREAD

**Issue by libertyy** [bridgecrewio/checkov-action#15]
Feature Request: 

action.yml to support --external-checks-dir and --external-checks-git

**Comment by mikelax** [comment]
I believe that this is currently supported if you configure the external checks in a checkov config file and the config file is used by the GitHub action. 

example snippet of `.checkov.yml` file
```yaml
external-checks-dir:
  - ./checkov_external_checks
```

**Comment by gruebel** [comment]
it can be used via
```yaml
  external_checks_dirs:
    description: 'comma separated list of external (custom) checks directories'
    required: false
  external_checks_repos:
    description: 'comma separated list of external (custom) checks repositories'
    required: false
```
