### ISSUE TITLE
Using skip_cve_package parameter with CVE-2023-46298 returns a failure

### ISSUE THREAD

**Issue by anastasialanz** [bridgecrewio/checkov-action#161]
When testing out the functionality of the `skip_cve_package` parameter, I set it to `CVE-2023-46298` to ignore this issue in the next.js package. After running the Checkov GitHub action, the PR still fails. Is there something else I would need to do to not have it fail?

Example `checkov.yml` GitHub Action

```
- name: Run Prisma Cloud
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@v12
        with:
          api-key: ***
          output_format: cli
          framework: github_actions,sca_package
          skip_cve_package: CVE-2023-46298
```
