### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by btilford** [bridgecrewio/checkov-action#22]
Would adding support for autodiscovery of terraform projects within a monrepo root or subdirectory be possible? Currently I've got 3 or 4 projects where I have to write several hundreds lines of yaml to manually add each project (also remembering to update yaml when a new project is added).

**Comment by metahertz** [comment]
Hi Ben,

Would something like the following allow you to just get the failed checks section of the json without a new flag?

```
checkov -o json -f terraform/aws/ec2.tf | jq .results.failed_checks 
```

```
checkov -o json -f terraform/aws/ec2.tf | jq .results.failed_checks > just_failed.json
```

**Comment by btilford** [comment]
I'm basically looking for something that includes directories/files to
check. Maybe an excludes would be easier to implement at least then things
can run a bit faster and dependencies/libs aren't being scanned recursively.

**Comment by njgibbon** [comment]
Hello @btilford 

I think we may be able to satisfy what you're after as-is. I'm not sure about excluding dirs yet. But checkout below:

I use this action configuration to run a recursive checkov scan only in the 'modules' directory. By specifying 'framework: terraform' I am only running terraform scans.
```
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/
          quiet: false
          soft_fail: false
          framework: terraform
          output_format: cli
```

Will this do what you want? You could do things like use several blocks if you want to choose different specific dirs and subdirs to scan.
