### ISSUE TITLE
Failed to Download

### ISSUE THREAD

**Issue by ArneRiemann4711** [bridgecrewio/checkov-action#39]
Hi, since yesterday we get an 403 when trying to use checkov action (-:

```
    - name: Terraform security check
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ${{ matrix.working_directory }}
          skip_check: CKV_AWS_65,CKV_AWS_51,CKV_AWS_23,CKV_AWS_85,CKV_AWS_40,CKV_AWS_52,CKV_AWS_21,CKV_AWS_18,CKV_AWS_107
          quiet: true # optional: display only failed checks
          framework: terraform
        continue-on-error: false
```

```
Failed to download action 'https://api.github.com/repos/bridgecrewio/checkov-action/tarball/60970bd282ce39baab17ecc3f6ccb67fd8b3bda3'. Error: Response status code does not indicate success: 403 (Forbidden).
```
