### ISSUE TITLE
Add the ability to define a container `--user` as an input

### ISSUE THREAD

**Issue by toast-gear** [bridgecrewio/checkov-action#58]
**Feature**
Add the ability to define a UID and GID to run the actions container on.

**Problem**
As it stands when you use this action the `.terraform` folder will have its owner set to `root root` as the container makes changes to the files. This then results in the next run of the workflow failing as the checkout action fails to delete the `.terraform` folder due to it being owned by `root root` rather than the user running the actions service.

To wokraround this you can use the action `peter-murray/reset-workspace-ownership-action` to reset the permissions on the repository code.

```yaml
      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo ::set-output name=uid::$actions_user_id
      - name: Correct Ownership in GITHUB_WORKSPACE directory
        uses: peter-murray/reset-workspace-ownership-action@v1
        with:
          user_id: ${{ steps.get_uid.outputs.uid }}
```

This is faff though and needs to be done in any workflow that uses this action. Would it be possible to add another optional input which lets you define the `--user` option so there is no need to use another action to deal with this issue?
