### ISSUE TITLE
Add a problem matcher

### ISSUE THREAD

**Issue by edhgoose** [bridgecrewio/checkov-action#6]
I'm not sure exactly how you'd do this, so it might be best just done in a README, but the following problem matcher will help parse the output:

```
{
    "problemMatcher": [
        {
            "owner": "checkov",
            "pattern": [
                {
                    "regexp": "^Check: (\\w+: .*)$",
                    "message": 1
                },
                {
                    "regexp": "^\\WFAILED.*$",
                },
                {
                    "regexp": "^\\WFile: \/(.+):(\\d+)-(\\d+)$",
                    "file": 1,
                    "line": 2
                }
            ]
        }
    ]
}
```

So that you get annotations like this:

<img width="1046" alt="Annotations on GitHub" src="https://user-images.githubusercontent.com/1108173/82498490-fe223900-9ae7-11ea-9f13-85f762232365.png">

I've added it by making my check look like this:

```
name: checkov
on: [pull_request]

jobs:
    checkov:
        runs-on: ubuntu-latest
        name: checkov-action
        steps:
            -
                name: Checkout repo
                uses: actions/checkout@v2

            -
                name: Setup Matcher
                run: echo "::add-matcher::./checkov/problem-matcher.json"

            -
                name: Run Checkov action
                id: checkov
                # I'm using v9, but you might want master or a later version!
                uses: bridgecrewio/checkov-action@v9
                with:
                    directory: ./
```

The json file is placed in `./checkov/problem-matcher.json`.

This commit here: https://github.com/actions/toolkit/commit/f90a2dcfd4dafd277f06c7da0741216d0ef13708, suggests that the right way to do it is to copy it out of the docker container, but I think you still have to add it manually in the workflow.
