### ISSUE TITLE
Feature: support SARIF output

### ISSUE THREAD

**Issue by hazcod** [bridgecrewio/checkov-action#67]
This enabled the Action to integrate with GitHub Security.

**Comment by wulfland** [comment]
SARIF is supported - but the file is not uploaded by default to GitHub. I think SARIF should be the default and the upload should be performed by the action. But the following code works:

```yaml
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        output_format: sarif
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
      if: always()
```
