### ISSUE TITLE
SARIF output format not documented and it should be the default output format for the action 

### ISSUE THREAD

**Issue by wulfland** [bridgecrewio/checkov-action#68]
SARIF is supported but not documented in the `action.yml` documentation of the `output_format` parameter:

```yaml
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        output_format: sarif
```

I think SARIF should be the default and the results should be uploaded to GitHub by the action so that the results show up under `Security` | `Code scanning alerts`. Right now you have to perform the  upload manually:
        
```yaml
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
      if: always()
```
