### ISSUE TITLE
Default --directory parameter overrides directory in .checkov.yml

### ISSUE THREAD

**Issue by nayoa** [bridgecrewio/checkov-action#77]
.checkov.yml:
```yaml
directory:
  - infra
evaluate-variables: true
framework: all
output: cli
quiet: true
download-external-modules: false
```
Action config:
```yaml
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: .checkov.yml
```
Expected outcome:
```bash
$ checkov --output sarif   --config-file .checkov.yml
```

Current outcome:
```bash
$ checkov -d .  --output sarif   --config-file .checkov.yml
```

**Comment by kartikp10** [comment]
Hey @nayoa, if the in-line --directory argument is overriding the config file, that behavior is by design. See the note at the bottom of `checkov --help`

```
Args that start with '--' (eg. -v) can also be set in a config file
(/Users/kpande/Downloads/.checkov.yaml or /Users/kpande/Downloads/.checkov.yml
or /Users/kpande/.checkov.yaml or /Users/kpande/.checkov.yml or specified via
--config-file). The config file uses YAML syntax and must represent a YAML
'mapping' (for details, see http://learn.getgrav.org/advanced/yaml). If an arg
is specified in more than one place, then commandline values override
environment variables which override config file values which override
defaults.
```
Let me know if that is not what you meant.

**Comment by ptchau2003** [comment]
@kartikp10 : The action is still on . directory instead of the directory mentioned in config.yaml
```
..
running checkov on directory: .
checkov -d .     --output sarif   --config-file .github/workflows/checkov_config.yaml  
..
```

**Comment by switchdk** [comment]
Although I experience the same problem and it is driving me nuts, I think the subject/title of this issue should more accurately reflect the problem. This is not about the `--directory` parameter but about the `directory` setting in `.checkov.yaml` being ignored (completely). It makes it impossible to use the checkov-action for larger repos or monorepos. As an example, I need to check Kubernetes manifests created with kustomize. However, if Checkov traverses all directories from `.` then Checkov will fail with a stacktrace due to how kustomize directory structure is and you can overwrite values. At the moment, the Checkov Action is unusable with kustomize repositories I think.

**Comment by liath** [comment]
It's kind of a dirty hack but you can set multiple values in `directory` by joining them with ` -d `:
```yaml
    - uses: bridgecrewio/checkov-action@v12
      id: checkov
      with:
        config_file: .checkov.yaml
        # Dirty hack to workaround: https://github.com/bridgecrewio/checkov-action/issues/77
        directory: first-folder -d second-folder
```
This works because the entrypoint script in the docker image this action calls [just plops inputs onto the command line](https://github.com/bridgecrewio/checkov/blob/main/github_action_resources/entrypoint.sh#L199C5-L199C21).
