### ISSUE TITLE
v12.1345 - Unable to find bridgecrew-problem-matcher.json

### ISSUE THREAD

**Issue by ravindra-bhadti-cko** [bridgecrewio/checkov-action#79]
For the latest version of the action release: https://github.com/bridgecrewio/checkov-action/tree/v12.1345.0

The following error is seen when trying to run the action:

```
Error: Unable to process command '::add-matcher::bridgecrew-problem-matcher.json' successfully.
Error: Could not find file '/home/runner/work/spacelift/spacelift/bridgecrew-problem-matcher.json'.
```

We're using it like this:
```
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: ${{ inputs.framework }}
          output_format: sarif # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          config_file: "${{ inputs.directory }}/${{ inputs.config_file }}"
```

**Comment by arogic** [comment]
We are having the same issues. Can you specify a Release Tag or version when using the GitHub Action?

Something like this:

```
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        version: v12
        with:
          framework: ${{ inputs.framework }}
          output_format: sarif # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          config_file: "${{ inputs.directory }}/${{ inputs.config_file }}"
```
