### ISSUE TITLE
Option to specify 'check' severity

### ISSUE THREAD

**Issue by the-tatanka** [bridgecrewio/checkov-action#83]
There is an option to check individual checks via their identifiers.
It would also be good if you could select the checks by their severity.

For example only "--check HIGH" as in https://github.com/bridgecrewio/checkov with "checkov -d . --check MEDIUM".

My current config is:
```
- name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true 
          soft_fail: false 
          framework: all
          output_format: sarif 
          download_external_modules: true
          log_level: WARNING 
          check: LOW # Results in - no checks applied
```

**Comment by rorysedgwick** [comment]
[This feature has been in Checkov itself for a few months now](https://bridgecrew.io/blog/checkov-iac-policy-severities-prioritize-skip-fail/) and for me is one of the most useful configuration options to have. Enabling this setting in the Github Action would be by far the lowest overhead to integrate checkov into existing IaC projects, and get meaningful but well-scoped feedback for new projects as well. 

Hope to see it feature here soon! 👍

**Comment by sbe-arg** [comment]
![image](https://user-images.githubusercontent.com/23391642/185540842-3a12c722-6eaa-414f-8b15-4e088f7a640d.png)

```yaml
      - name: tests-checkov-sam
        if: hashFiles('**/serverless.yml') != ''
        uses: bridgecrewio/checkov-action@v12
        with:
          check: 'MEDIUM,HIGH,CRITICAL'
```
