### ISSUE TITLE
Add option for stderr supression

### ISSUE THREAD

**Issue by johannesclaesson** [bridgecrewio/checkov-action#85]
Some frameworks can generate incorrect parse errors. This leads to often unwanted python exception spam. This can be supressed simply by redirecting stderr to /dev/null when running checkov from command line. When using checkov-action, however, I fail to see such an option.

**Comment by gruebel** [comment]
you can set the log level to `CRITICAL` and then you will not see any parsing error logs 🙂 
```yaml
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          log_level: CRITICAL
```
