### ISSUE TITLE
Feature Request: Support `--repo-root-for-plan-enrichment` option

### ISSUE THREAD

**Issue by fleroux514** [bridgecrewio/checkov-action#99]
Tried to use the Github Action as this:
```
      - name: Run Checkov action on Terraform plan output
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          repo_root_for_plan_enrichment: .
```

and got the following error:

![image](https://user-images.githubusercontent.com/17277004/191348391-bed5fc9b-cd2a-4a69-bc55-1ec91498ab03.png)
